local_costmap:
   global_frame: world
   robot_base_frame: base_link
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true